export default {
  board: { main: "board" },
  note: {
    main: "note",
    description: "note__description",
    container: "note_container",
    btn: "note__btn",
    changeStatusBtn: "note__change_status_btn",
    activateStatusBtn: "note__change_status_btn--activate",
    deactivateStatusBtn: "note__change_status_btn--deactivate",
    deleteBtn: "note__delete_btn",
    pin: "note__pin",
    icon: "note__icon",
    status: "note__status",
    type: "note__type",
  },
  noteOption: { main: "note_option" },
  noteFormPopUpTrigger: { main: "note_form_popup_trigger" },
  noteDeleteAllTrigger: { main: "note_delete_trigger" },
  noteFormPopUp: {
    main: "note_popup_container",
    active: "note_popup_container--active",
    closeBtn: "note_popup__close_btn",
  },
  noteForm: {
    main: "note_form",
    submitBtn: "note_form__btn",
    noteColorInput: "note_form__color_input",
  },
  noteSearch: {
    searchInput: "note_search__input",
    icon: "note_search__icon",
    cancelBtn: "note_search__cancel_btn",
  },
  icon: {
    main: "fas",
    detailed: "fa-",
    delete: "fa-trash",
  },
  loader: {
    container: "loader_container",
    main: "loader",
    item: "loader__item",
    blueItem: "loader__item--blue",
    purpleItem: "loader__item--purple",
    yellowItem: "loader__item--yellow",
    redItem: "loader__item--red",
    text: "loader__text",
  },
  draggable: {
    main: "draggable",
  },
};
